source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod "AFNetworking", "~> 2.5.0"
pod 'iCarousel', '~> 1.8'
pod 'Mantle', '1.4.1'
pod 'SDWebImage'
pod 'UICKeyChainStore'
pod 'Masonry'
pod 'JSQMessagesViewController'
pod 'HMSegmentedControl', :git => 'https://github.com/SJApps/HMSegmentedControl'
pod 'YIPopupTextView'
pod 'UIAlertView+Blocks'
pod 'UIActionSheet+Blocks'
pod 'CKCalendar', :git => 'https://github.com/SJApps/CKCalendar.git'
pod 'Analytics/Mixpanel', '1.5.10'
pod 'Analytics/Localytics'
pod 'SVProgressHUD', :head
pod 'apptentive-ios'
pod 'JVFloatLabeledTextField'
pod 'NSLogger'
pod 'UIImageViewAligned', :git => 'https://github.com/reydanro/UIImageViewAligned'
pod 'BBBadgeBarButtonItem'
pod 'AMSlideOutController'
pod 'CardIO'